### PR TITLE
Make SteemConnect instance based

### PR DESCRIPTION
**Pull request by Sekhmet**
Currently, `sc2-sdk` uses a global scope for storing its state. It's not considered good practice as it makes it impossible to run two different instances of it at the same time. This behaviour is required to implement an application that has to handle dozens of instances of `sc2-sdk` running with a different configuration (e.g. server-side rendering).
This PR changes the way sc2-sdk works, instead of configuring global instance you create a new one using `Initialize(config)` method.
I think that this change should bump the version of the library to `1.0.0` per semver versioning scheme.

### CODE REVIEW

**Comment by bonustrack** [comment]
Can we have the README updated accordingly?

**Comment by Sekhmet** [comment]
Should I bump version in this PR as well?

**Comment by bonustrack** [comment]
Yes @Sekhmet

**Comment by Sekhmet** [comment]
@bonustrack updated documentation and added changelog.

**Pull request merged**
